
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSOMASUBTRACAOleftMULTIPLICACAODIVISAOABRE_PARENTESES DIVISAO FECHA_PARENTESES MULTIPLICACAO NUMERO SOMA SUBTRACAO\n    programa : expressao\n    \n    expressao : expressao SOMA expressao\n              | expressao SUBTRACAO expressao\n              | expressao MULTIPLICACAO expressao\n              | expressao DIVISAO expressao\n    \n    expressao : NUMERO\n    \n    expressao : ABRE_PARENTESES expressao FECHA_PARENTESES\n    '
    
_lr_action_items = {'NUMERO':([0,4,5,6,7,8,],[3,3,3,3,3,3,]),'ABRE_PARENTESES':([0,4,5,6,7,8,],[4,4,4,4,4,4,]),'$end':([1,2,3,10,11,12,13,14,],[0,-1,-6,-2,-3,-4,-5,-7,]),'SOMA':([2,3,9,10,11,12,13,14,],[5,-6,5,-2,-3,-4,-5,-7,]),'SUBTRACAO':([2,3,9,10,11,12,13,14,],[6,-6,6,-2,-3,-4,-5,-7,]),'MULTIPLICACAO':([2,3,9,10,11,12,13,14,],[7,-6,7,7,7,-4,-5,-7,]),'DIVISAO':([2,3,9,10,11,12,13,14,],[8,-6,8,8,8,-4,-5,-7,]),'FECHA_PARENTESES':([3,9,10,11,12,13,14,],[-6,14,-2,-3,-4,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'expressao':([0,4,5,6,7,8,],[2,9,10,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> expressao','programa',1,'p_programa','sintatico.py',13),
  ('expressao -> expressao SOMA expressao','expressao',3,'p_expressao','sintatico.py',20),
  ('expressao -> expressao SUBTRACAO expressao','expressao',3,'p_expressao','sintatico.py',21),
  ('expressao -> expressao MULTIPLICACAO expressao','expressao',3,'p_expressao','sintatico.py',22),
  ('expressao -> expressao DIVISAO expressao','expressao',3,'p_expressao','sintatico.py',23),
  ('expressao -> NUMERO','expressao',1,'p_expressao_numero','sintatico.py',37),
  ('expressao -> ABRE_PARENTESES expressao FECHA_PARENTESES','expressao',3,'p_expressao_parenteses','sintatico.py',44),
]
